Repository lava-nc/lava, pull requests merged in 2022-02, with the labels that each got.

#156 Implementation of ReadVar and ResetVar IO process and bugfixes for LIF, Dense and Conv processes
  src/lava/proc/conv/models.py
  src/lava/proc/conv/process.py
  src/lava/proc/dense/models.py
  src/lava/proc/dense/process.py
  src/lava/proc/io/__init__.py
  src/lava/proc/io/reset.py
  src/lava/proc/io/sink.py
  src/lava/proc/io/source.py
  src/lava/proc/lif/models.py
  src/lava/proc/lif/process.py
  tests/lava/proc/conv/test_models.py
  tests/lava/proc/io/test_source_sink.py
  tests/lava/proc/lif/test_models.py
Labels: enhancement, needs-review

#147 Improve mnist tutorial
  tutorials/end_to_end/tutorial01_mnist_digit_classification.ipynb
Labels: enhancement, needs-review, tutorial

#177 Multiproc bug
  src/lava/magma/runtime/message_infrastructure/multiprocessing.py
Labels: bug, runtime

#131 Refactoring py/ports
  src/lava/magma/compiler/builders/builder.py
  src/lava/magma/compiler/compiler.py
  src/lava/magma/core/model/py/ports.py
  src/lava/magma/core/process/ports/ports.py
  tests/lava/magma/core/model/py/test_ports.py
  tests/lava/magma/core/model/test_py_model.py
Labels: enhancement, needs-review

#182 Add NxSDKRuntimeService
  src/lava/magma/compiler/builders/builder.py
  src/lava/magma/compiler/builders/interfaces.py
  src/lava/magma/compiler/compiler.py
  src/lava/magma/core/model/interfaces.py
  src/lava/magma/core/model/model.py
  src/lava/magma/core/model/nc/model.py
  src/lava/magma/core/model/nc/type.py
  src/lava/magma/core/model/py/model.py
  src/lava/magma/core/process/process.py
  src/lava/magma/core/resources.py
  src/lava/magma/core/run_configs.py
  src/lava/magma/core/sync/protocols/async_protocol.py
  src/lava/magma/core/sync/protocols/loihi_protocol.py
  src/lava/magma/runtime/runtime.py
  src/lava/magma/runtime/runtime_services/enums.py
  src/lava/magma/runtime/runtime_services/interfaces.py
  src/lava/magma/runtime/runtime_services/runtime_service.py
  tests/lava/magma/compiler/test_compiler.py
  tests/lava/magma/core/process/test_lif_dense_lif.py
  tests/lava/magma/runtime/test_exception_handling.py
  tests/lava/magma/runtime/test_get_set_var.py
  tests/lava/magma/runtime/test_nxsdkruntimeservice_loihi.py
  tests/lava/magma/runtime/test_ref_var_ports.py
  tests/lava/magma/runtime/test_runtime.py
  tests/lava/magma/runtime/test_runtime_service.py
  tests/lava/proc/io/test_dataloader.py
  tests/lava/test_utils/__init__.py
  tests/lava/test_utils/utils.py
Labels: runtime, compiler

#187 Partial implementation of virtual ports for PyProcModels
  src/lava/magma/compiler/builders/builder.py
  src/lava/magma/compiler/compiler.py
  src/lava/magma/compiler/utils.py
  src/lava/magma/core/model/py/ports.py
  src/lava/magma/core/process/ports/exceptions.py
  src/lava/magma/core/process/ports/ports.py
  tests/lava/magma/core/model/py/test_ports.py
  tests/lava/magma/core/process/ports/__init__.py
  tests/lava/magma/core/process/ports/test_ports.py
  tests/lava/magma/core/process/ports/test_virtual_ports_in_process.py
  tests/lava/magma/core/process/test_virtual_ports_in_process.py
Labels: enhancement, help wanted

#190 Fixing priority of channel commands in model
  src/lava/magma/core/model/py/model.py
Labels: bug
